version: "3.9"

services:
  app:
    build: .
    container_name: stego-app
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    container_name: stego-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
